export const INIT_FEEDBACK_POWER_STATION_LIST = "INIT_FEEDBACK_POWER_STATION_LIST"

export const INIT_FEEDBACK_DEVICE_TYPES = "INIT_FEEDBACK_DEVICE_TYPES"

export const INIT_FEEDBACK_DEVICE_NUMBER = "INIT_FEEDBACK_DEVICE_NUMBER"