/**
 * @component actionType.js
 * @description redux 动作常量
 * @time 2017-06-18 20:40
 * @author fishYu
 **/
export const HOME_CHANGE_TAB = "HOME_CHANGE_TAB"

export const REQUEST_HOME_DATA = 'REQUEST_HOME_DATA';

export const RECEIVE_HOME_CONTAINER_DATA = "RECEIVE_HOME_CONTAINER_DATA"; //首页
export const RECEIVE_WORK_ORDER_DATA = "RECEIVE_WORK_ORDER_DATA";   //工单消息
export const RECEIVE_MESSAGE_CENTER_DATA = "RECEIVE_MESSAGE_CENTER_DATA";  //消息中心

export const RECEIVE_PERSONAL_CENTER_DATA = "RECEIVE_PERSONAL_CENTER_DATA";  //个人中心

//首页报警列表
export const HOME_INIT_ALARM_LIST = "HOME_INIT_ALARM_LIST"
//首页公告
export const HOME_INIT_NOTICE_LIST = "HOME_INIT_NOTICE_LIST"
//首页未读报警数量
export const HOME_INIT_ALARM_COUNT = "HOME_INIT_ALARM_COUNT"
//用户电站列表
export const HOME_INIT_USER_POWER_STATION = "HOME_INIT_USER_POWER_STATION"
//首页7日工单完成量
export const HOME_INIT_WORKORDER_COMPLETION = "HOME_INIT_WORKORDER_COMPLETION"